<a href="https://colab.research.google.com/github/mvuddandi/ML-StatModels/blob/main/One_hot_encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/mvuddandi/ML-StatModels.git

Cloning into 'ML-StatModels'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 48 (delta 21), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (48/48), 69.35 KiB | 2.04 MiB/s, done.
Resolving deltas: 100% (21/21), done.


In [2]:
%cd ML-StatModels/

/content/ML-StatModels


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [4]:
df = pd.read_csv("homeprices.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   town    13 non-null     object
 1   area    13 non-null     int64 
 2   price   13 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 444.0+ bytes


In [5]:
town_dummy = pd.get_dummies(df.town, dtype=int)
town_dummy

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [6]:
df_merged = pd.concat([df,town_dummy],axis="columns")
df_merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [7]:
df_mer1 = df_merged

In [8]:
df_mer1 = df_mer1.drop(['town','west windsor'], axis='columns')


In [9]:
df_mer1

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [10]:
model = linear_model.LinearRegression()

In [11]:
X = df_mer1.drop('price', axis='columns')
y = df_mer1.price
model.fit (X,y)

LinearRegression()

In [12]:
model.predict([[3000,1,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590468.71640508])

In [13]:
model.score (X,y)

0.9573929037221872

Using the one hot encode



In [14]:
from sklearn .preprocessing import LabelEncoder

le = LabelEncoder()

In [24]:
df_mer2 = df
df_mer2

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [25]:
df_mer2.town = le.fit_transform(df_mer2.town)

df_mer2

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [26]:
X = df_mer2[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [27]:
y = df_mer2.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(sparse_output=False), ['town'])
    ],
    remainder='passthrough'
)

X_transformed = ct.fit_transform(df)


In [38]:
X_transformed

array([[1.00e+00, 0.00e+00, 0.00e+00, 2.60e+03, 5.50e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.00e+03, 5.65e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.20e+03, 6.10e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.60e+03, 6.80e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.00e+03, 7.25e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.60e+03, 5.85e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.80e+03, 6.15e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.30e+03, 6.50e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.60e+03, 7.10e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.60e+03, 5.75e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.90e+03, 6.00e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.10e+03, 6.20e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.60e+03, 6.95e+05]])

In [40]:
X_transformed = X_transformed[:,1:]
X_transformed

array([[0.00e+00, 2.60e+03, 5.50e+05],
       [0.00e+00, 3.00e+03, 5.65e+05],
       [0.00e+00, 3.20e+03, 6.10e+05],
       [0.00e+00, 3.60e+03, 6.80e+05],
       [0.00e+00, 4.00e+03, 7.25e+05],
       [1.00e+00, 2.60e+03, 5.85e+05],
       [1.00e+00, 2.80e+03, 6.15e+05],
       [1.00e+00, 3.30e+03, 6.50e+05],
       [1.00e+00, 3.60e+03, 7.10e+05],
       [0.00e+00, 2.60e+03, 5.75e+05],
       [0.00e+00, 2.90e+03, 6.00e+05],
       [0.00e+00, 3.10e+03, 6.20e+05],
       [0.00e+00, 3.60e+03, 6.95e+05]])

In [41]:
model.fit(X_transformed,y)

LinearRegression()

In [47]:
model.predict([[1,0,2600]])


array([2600.])